### ISSUE TITLE
Can't start session from tty

### ISSUE THREAD

**Issue by Svadkos** [giucam/orbital#35]
```
[W  - /tmp/makepkg/orbital-git/src/orbital/src/authorizer_helper/main.cpp:167] == No orbital_authorizer_helper interface.
```

**Comment by giucam** [comment]
That message is not relevant. Please post the full log.

**Comment by Svadkos** [comment]
From shell
```
initializing drm backend
using /dev/dri/card0
Loading module '/usr/lib/weston-1/gl-renderer.so'
EGL client extensions: EGL_EXT_client_extensions EGL_EXT_platform_base
               EGL_EXT_platform_wayland EGL_EXT_platform_x11
               EGL_KHR_client_get_all_proc_addresses EGL_MESA_platform_gbm
warning: EGL_EXT_swap_buffers_with_damage not supported. Performance could be affected.
input device 'Power Button', /dev/input/event10 is tagged by udev as: Keyboard
input device 'Power Button', /dev/input/event10 is a keyboard
input device 'Power Button', /dev/input/event9 is tagged by udev as: Keyboard
input device 'Power Button', /dev/input/event9 is a keyboard
input device 'HDA ATI HDMI HDMI/DP,pcm=11', /dev/input/event8 not tagged as input device
failed to create input device '/dev/input/event8'.
input device 'HDA ATI HDMI HDMI/DP,pcm=3', /dev/input/event3 not tagged as input device
failed to create input device '/dev/input/event3'.
input device 'HDA ATI HDMI HDMI/DP,pcm=7', /dev/input/event4 not tagged as input device
failed to create input device '/dev/input/event4'.
input device 'HDA ATI HDMI HDMI/DP,pcm=8', /dev/input/event5 not tagged as input device
failed to create input device '/dev/input/event5'.
input device 'HDA ATI HDMI HDMI/DP,pcm=9', /dev/input/event6 not tagged as input device
failed to create input device '/dev/input/event6'.
input device 'HDA ATI HDMI HDMI/DP,pcm=10', /dev/input/event7 not tagged as input device
failed to create input device '/dev/input/event7'.
input device 'PixArt USB Optical Mouse', /dev/input/event2 is tagged by udev as: Mouse
Device 'PixArt USB Optical Mouse' set to 1000 DPI
input device 'PixArt USB Optical Mouse', /dev/input/event2 is a pointer caps
input device 'HID 0566:3107', /dev/input/event0 is tagged by udev as: Keyboard
input device 'HID 0566:3107', /dev/input/event0 is a keyboard
input device 'HID 0566:3107', /dev/input/event1 is tagged by udev as: Keyboard
input device 'HID 0566:3107', /dev/input/event1 is a keyboard
input device 'HD-Audio Generic Front Mic', /dev/input/event11 not tagged as input device
failed to create input device '/dev/input/event11'.
input device 'HD-Audio Generic Rear Mic', /dev/input/event12 not tagged as input device
failed to create input device '/dev/input/event12'.
input device 'HD-Audio Generic Line', /dev/input/event13 not tagged as input device
failed to create input device '/dev/input/event13'.
input device 'HD-Audio Generic Line Out', /dev/input/event14 not tagged as input device
failed to create input device '/dev/input/event14'.
input device 'HD-Audio Generic Front Headphone', /dev/input/event15 not tagged as input device
failed to create input device '/dev/input/event15'.
input device 'PC Speaker', /dev/input/event16 not tagged as input device
failed to create input device '/dev/input/event16'.
EGL version: 1.4 (DRI2)
EGL vendor: Mesa Project
EGL client APIs: OpenGL OpenGL_ES OpenGL_ES2 OpenGL_ES3 
EGL extensions: EGL_EXT_buffer_age EGL_EXT_image_dma_buf_import
               EGL_KHR_create_context EGL_KHR_get_all_proc_addresses
               EGL_KHR_gl_renderbuffer_image EGL_KHR_gl_texture_2D_image
               EGL_KHR_gl_texture_cubemap_image EGL_KHR_image
               EGL_KHR_image_base EGL_KHR_image_pixmap
               EGL_KHR_surfaceless_context EGL_MESA_configless_context
               EGL_MESA_drm_image EGL_MESA_image_dma_buf_export
               EGL_WL_bind_wayland_display
GL version: OpenGL ES 3.0 Mesa 11.2.2
GLSL version: OpenGL ES GLSL ES 3.00
GL vendor: X.Org
GL renderer: Gallium 0.4 on AMD CAPE VERDE (DRM 2.43.0, LLVM 3.8.0)
GL extensions: GL_EXT_blend_minmax GL_EXT_multi_draw_arrays
               GL_EXT_texture_filter_anisotropic
               GL_EXT_texture_compression_dxt1 GL_EXT_texture_format_BGRA8888
               GL_OES_compressed_ETC1_RGB8_texture GL_OES_depth24
               GL_OES_element_index_uint GL_OES_fbo_render_mipmap
               GL_OES_mapbuffer GL_OES_rgb8_rgba8 GL_OES_standard_derivatives
               GL_OES_stencil8 GL_OES_texture_3D GL_OES_texture_float
               GL_OES_texture_float_linear GL_OES_texture_half_float
               GL_OES_texture_half_float_linear GL_OES_texture_npot
               GL_OES_EGL_image GL_OES_depth_texture
               GL_OES_packed_depth_stencil GL_EXT_texture_type_2_10_10_10_REV
               GL_OES_get_program_binary GL_APPLE_texture_max_level
               GL_EXT_discard_framebuffer GL_EXT_read_format_bgra
               GL_NV_fbo_color_attachments GL_OES_EGL_image_external
               GL_OES_EGL_sync GL_OES_vertex_array_object
               GL_ANGLE_texture_compression_dxt3
               GL_ANGLE_texture_compression_dxt5 GL_EXT_texture_rg
               GL_EXT_unpack_subimage GL_NV_draw_buffers GL_NV_read_buffer
               GL_NV_read_depth GL_NV_read_depth_stencil GL_NV_read_stencil
               GL_EXT_draw_buffers GL_EXT_map_buffer_range GL_KHR_debug
               GL_OES_depth_texture_cube_map GL_OES_surfaceless_context
               GL_EXT_color_buffer_float GL_EXT_separate_shader_objects
               GL_EXT_shader_integer_mix GL_EXT_draw_elements_base_vertex
               GL_KHR_context_flush_control GL_OES_draw_elements_base_vertex
               GL_OES_texture_stencil8 GL_EXT_blend_func_extended
GL ES 2 renderer features:
               read-back format: BGRA
               wl_shm sub-image to texture: yes
               EGL Wayland extension: yes
Chosen EGL config details:
               RGBA bits: 8 8 8 0
               swap interval range: 0 - 0
Failed to initialize backlight
EDID data 'BNQ', 'BENQ G2320HD', 'R9A03657019'
Output DVI1, (connector 45, crtc 29)
               mode 1920x1080@60,0, preferred, current
               mode 1600x1200@60,0
               mode 1680x1050@60,0
               mode 1280x1024@75,0
               mode 1280x1024@60,0
               mode 1440x900@59,9
               mode 1280x960@60,0
               mode 1152x864@75,0
               mode 1280x720@60,0
               mode 1024x768@75,1
               mode 1024x768@60,0
               mode 1024x576@60,0
               mode 832x624@74,6
               mode 800x600@75,0
               mode 800x600@60,3
               mode 640x480@75,0
               mode 640x480@60,0
               mode 720x400@70,1
Using 'wayland-0'
Launching '/usr/libexec/orbital-authorizer-helper'...
unlinking stale lock file /tmp/.X0-lock
xserver listening on display :0
Launching '/usr/libexec/orbital-splash'...
Launching '/usr/libexec/startorbital'...
Autostarting ''
```
From journalctl
```
май 19 23:12:44 desktop systemd[1]: Started Process Core Dump (PID 13724/UID 0).
май 19 23:12:44 desktop kernel: orbital-splash[13721]: segfault at 8 ip 00007f7f9f9e0f20 sp 00007ffd4bbf3f18 error 4 in libQt5Gui.so.5.6.0[7f7f9f8bb000+563000]
май 19 23:12:44 desktop kernel: orbital-client[13722]: segfault at 8 ip 00007f0bf2130f20 sp 00007ffdffee1b68 error 4 in libQt5Gui.so.5.6.0[7f0bf200b000+563000]
май 19 23:12:44 desktop systemd[1]: Started Process Core Dump (PID 13728/UID 0).
май 19 23:12:44 desktop systemd[1]: Started Process Core Dump (PID 13730/UID 0).
май 19 23:12:45 desktop systemd-coredump[13725]: Process 13713 (orbital) of user 1000 dumped core.
                                                    
                                                    Stack trace of thread 13713:
                                                    #0  0x00007f95978ae295 raise (libc.so.6)
                                                    #1  0x00007f95978af6da abort (libc.so.6)
                                                    #2  0x0000558ba7d38b66 n/a (orbital)
                                                    #3  0x0000558ba7d38b9e n/a (orbital)
                                                    #4  0x00007f95978ae310 __restore_rt (libc.so.6)
                                                    #5  0x0000558ba7d601f7 _ZNSt7__cxx1115basic_stringbufIcSt11char_traitsIcESaIcEED2Ev (orbital)
                                                    #6  0x0000558ba7d5121d n/a (orbital)
                                                    #7  0x0000558ba7d51a3a _ZN7Orbital5Shell16autostartClientsEv (orbital)
                                                    #8  0x0000558ba7d4f9cd _ZN7Orbital5ShellC2EPNS_10CompositorE (orbital)
                                                    #9  0x0000558ba7d3a9ab _ZN7Orbital10Compositor4initENS_10StringViewE (orbital)
                                                    #10 0x0000558ba7d3238a main (orbital)
                                                    #11 0x00007f959789b741 __libc_start_main (libc.so.6)
                                                    #12 0x0000558ba7d317d9 _start (orbital)
                                                    
                                                    Stack trace of thread 13719:
                                                    #0  0x00007f959746009f pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                                                    #1  0x00007f958b62a0a3 n/a (radeonsi_dri.so)
                                                    #2  0x00007f958b6297e7 n/a (radeonsi_dri.so)
                                                    #3  0x00007f959745a474 start_thread (libpthread.so.0)
                                                    #4  0x00007f959796269d __clone (libc.so.6)
май 19 23:12:45 desktop systemd-coredump[13729]: Process 13721 (orbital-splash) of user 1000 dumped core.
                                                    
                                                    Stack trace of thread 13721:
                                                    #0  0x00007f7f9f9e0f20 _ZNK7QScreen6handleEv (libQt5Gui.so.5)
                                                    #1  0x00007f7f9f9f1d32 _ZN15QHighDpiScaling20updateHighDpiScalingEv (libQt5Gui.so.5)
                                                    #2  0x00007f7f9f472674 _ZN16QCoreApplication4initEv (libQt5Core.so.5)
                                                    #3  0x00007f7f9f472886 _ZN16QCoreApplicationC2ER23QCoreApplicationPrivate (libQt5Core.so.5)
                                                    #4  0x00007f7f9f9b583d _ZN15QGuiApplicationC2ERiPPci (libQt5Gui.so.5)
                                                    #5  0x00005604f455bbb0 main (orbital-splash)
                                                    #6  0x00007f7f9e8c3741 __libc_start_main (libc.so.6)
                                                    #7  0x00005604f455b459 _start (orbital-splash)
май 19 23:12:45 desktop systemd-coredump[13735]: Process 13722 (orbital-client) of user 1000 dumped core.
                                                    
                                                    Stack trace of thread 13722:
                                                    #0  0x00007f0bf2130f20 _ZNK7QScreen6handleEv (libQt5Gui.so.5)
                                                    #1  0x00007f0bf2141d32 _ZN15QHighDpiScaling20updateHighDpiScalingEv (libQt5Gui.so.5)
                                                    #2  0x00007f0bf1bc2674 _ZN16QCoreApplication4initEv (libQt5Core.so.5)
                                                    #3  0x00007f0bf1bc2886 _ZN16QCoreApplicationC2ER23QCoreApplicationPrivate (libQt5Core.so.5)
                                                    #4  0x00007f0bf2105889 _ZN15QGuiApplicationC2ER22QGuiApplicationPrivate (libQt5Gui.so.5)
                                                    #5  0x00007f0bf36dadad _ZN12QApplicationC1ERiPPci (libQt5Widgets.so.5)
                                                    #6  0x0000564d2bda5ce0 main (orbital-client)
                                                    #7  0x00007f0bf1013741 __libc_start_main (libc.so.6)
                                                    #8  0x0000564d2bda5b69 _start (orbital-client)
```

**Comment by giucam** [comment]
Can you get a backtrace with "coredumpctl gdb orbital", and by running "bt" in it?

**Comment by Svadkos** [comment]
```
#0  0x00007f34a95b8295 in raise () from /usr/lib/libc.so.6
#1  0x00007f34a95b96da in abort () from /usr/lib/libc.so.6
#2  0x0000556b3550cb66 in ?? ()
#3  0x0000556b3550cb9e in ?? ()
#4  <signal handler called>
#5  0x00007f34a9f71d71 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find (this=0x7ffc5b035eb0, __c=10 '\n', __pos=0)
    at /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/basic_string.tcc:1200
#6  0x0000556b35524fb2 in ?? ()
#7  0x0000556b35525a3a in Orbital::Shell::autostartClients() ()
#8  0x0000556b355239cd in Orbital::Shell::Shell(Orbital::Compositor*) ()
#9  0x0000556b3550e9ab in Orbital::Compositor::init(Orbital::StringView) ()
#10 0x0000556b3550638a in main ()

```

**Comment by giucam** [comment]
you're missing the debug symbols, it's not very useful like that. please fix it, or alternatively put the coredump file somewhere i can download it.

**Comment by Svadkos** [comment]
Alright
#0  0x00007f6a85a50295 in raise () from /usr/lib/libc.so.6
#1  0x00007f6a85a516da in abort () from /usr/lib/libc.so.6
#2  0x000055a092bccb66 in Orbital::Compositor::<lambda(int)>::operator()(int) const (__closure=0x0)
    at /tmp/makepkg/orbital-git/src/orbital/src/compositor/compositor.cpp:250
#3  0x000055a092bccb9e in Orbital::Compositor::<lambda(int)>::_FUN(int) ()
    at /tmp/makepkg/orbital-git/src/orbital/src/compositor/compositor.cpp:253
#4  <signal handler called>
#5  0x00007f6a86371324 in std::istream::ignoreXX (this=0x7ffefee7ddd0, __n=1)
    at /build/gcc/src/gcc/libstdc++-v3/src/c++98/compatibility.cc:62
#6  0x000055a092be4f6e in Orbital::readDesktopFile (stream=..., map=std::unordered_map with 8 elements = {...})
    at /tmp/makepkg/orbital-git/src/orbital/src/compositor/shell.cpp:216
#7  0x000055a092be5a3a in Orbital::Shell::autostartClients (this=0x55a093e0a270)
    at /tmp/makepkg/orbital-git/src/orbital/src/compositor/shell.cpp:279
#8  0x000055a092be39cd in Orbital::Shell::Shell (this=0x55a093e0a270, c=0x7ffefee7e4c0)
    at /tmp/makepkg/orbital-git/src/orbital/src/compositor/shell.cpp:103
#9  0x000055a092bce9ab in Orbital::Compositor::init (this=0x7ffefee7e4c0, socketName=...)
    at /tmp/makepkg/orbital-git/src/orbital/src/compositor/compositor.cpp:471
#10 0x000055a092bc638a in main (argc=1, argv=0x7ffefee7e768)
    at /tmp/makepkg/orbital-git/src/orbital/src/compositor/main.cpp:70

**Comment by giucam** [comment]
I've done a lot of changes in the last few days, can you try those? You'll need to update the patched weston too.

**Comment by Svadkos** [comment]
It launched, but i met to problems not related to this topic:
1. command 'orbital-launch' no longer worksб instead 'orbital launch' works
2. I'm not sure that this is issue, but is it supposed to launch kde plasma on top of orbital workspace, if it were some kind of window? Look's wierd.

**Comment by giucam** [comment]
1: indeed, orbital-launch is not available for now. but just launching orbital works, if you have logind. Running "orbital lunch" just ignores the "launch".

2: mmh no, it's not supposed to launch plasma. Can you open a new issue with a screenshot?

Since this is fixed i'll close it.
